### ISSUE TITLE
Https certificate setup

### ISSUE THREAD

**Issue by ChadIImus** [ChadIImus/Devoops#11]

**Comment by ChadIImus** [comment]
Should probably be part of the provisioning to make the droplet serve the certificate on port 443, maybe with nginx?
The certificate itself can be created beforehand with something like certbot.

But that requires we have something initiating the certificate challenge proving we control that ip, before provisioning the droplet, which might be done manually, even though that makes automatic provisioning a little moot.

**Comment by Thomsen96** [comment]
I see that you have marked the issue at wontfix. 

But when you have set your DNS to point at your floating ip can you use the tool [cert bot](https://certbot.eff.org/) to get certificates from [Let's encrypt](https://letsencrypt.org/)

like so: https://github.com/DevelOpsITU/ServerDeployment/blob/7ee9c482108ce87bac6c4e586fb75f6cfb0614de/ApplicationServer/init.sh#L15

**Comment by Wayhowen** [comment]
Hi, 

Unfortunately, we are unable to fix this as of now, because of a lack of resources.

On the other hand, we would be really happy if you could make a PR incorporating the mentioned changes for us!

Best wishes,
ASPirin

**Comment by Thomsen96** [comment]
Hi, 

I would like to implement it. But my group are also under great lack of resources. So i therefore don't have time to make a PR. 

And also setting it up is a great exercise for the reader ;)
