### ISSUE TITLE
Optimize simulator API for E-PEEN

### ISSUE THREAD

**Issue by ChadIImus** [ChadIImus/Devoops#15]

**Comment by ChadIImus** [comment]
Introduced new index on follows entity because of readtimeouts when running the simulator.
Also removed sign on register.

**Comment by ChadIImus** [comment]
Generate the queries that EF core generates from our LINQ code and profile them on the postgres database

**Comment by koshaan** [comment]
lange willy

**Comment by ChadIImus** [comment]
We ended up in 3rd place, most likely because of our managed database being on a separate machine from our application. Which our two competitors seemed to host locally on the same machine as their application. To continue this optimication we would have needed the pr. endpoint profiling which is referenced here:
https://github.com/ChadIImus/Devoops/issues/93
