### ISSUE TITLE
Grafana dashboard showing Prometheus data

### ISSUE THREAD

**Issue by julianbrandt** [ChadIImus/Devoops#28]

**Comment by ChadIImus** [comment]
1. Collect metrics .✔
2. Consume/persist metrics (with prometheus server)✔
3. Display metrics on grafana (needs to configure dashboard)

**Comment by ChadIImus** [comment]
All metrics from the c# application are shown on the dashboard here:
http://shittymetrics.tk

Needs to add queries to the database for users and average follows etc.

**Comment by Wayhowen** [comment]
Queries from the database have been added.
Some new metrics regarding system and requests added.
Provisioning now uses new data source || for some reason I couldn't make the provisioning pick all of the keywords up, so we still need to manually change password, version and SSL requirement.
Added rows to split the dashboard into more digestable parts

**Comment by ChadIImus** [comment]
TODO:
Uptime metric that runs outside the application and pings if it is alive
Alert on that metric that notifies the team via fx. email or sysadmin home speaker

**Comment by Wayhowen** [comment]
Alerting via discord on application down added
Changes to Vagrant file to prevent further attacks
Provisioning of alerts couldn't be added because of issues introduced by Grafana creators
