### ISSUE TITLE
Feedback from group D

### ISSUE THREAD

**Issue by Lucki2g** [ChadIImus/Devoops#35]
- [x] Do you see a public timeline?
- [x] Does the public timeline show messages that the application received from the simulator?
- [x] Can you create a new user?
- [x] Can you login as a new user?
- [x] Can you write a message?
- [x] After publishing a message, does it appear on you private timeline?
- [x] Can you follow another user?

Doing "illegal" operations, e.g. trying to sign in with a non existing user sends you to and empty page with an error message. You may want to use a type of label, like the original minitwit application.
![image](https://user-images.githubusercontent.com/11597762/158372431-49525c53-318a-4727-bd8f-9d10244fbd6a.png)
**[EDIT]** now it redirects to page
![image](https://user-images.githubusercontent.com/11597762/158372806-09881725-af73-41f1-a567-885a874ae217.png)

We cannot figure out what the remember me button is doing, it seems the user is always remembered and stays signed in, even after closing the window and reopening it.

**Comment by ChadIImus** [comment]
The remember me says that the cookie will last indefinetly (or close to it),
and the default login uses a cookie that lives for i think around 15 minutes.

**Comment by koshaan** [comment]
tak brors
