### ISSUE TITLE
DigitalOcean Droplet

### ISSUE THREAD

**Issue by koshaan** [ChadIImus/Devoops#4]
Create droplet and then deploy the app there

**Comment by ChadIImus** [comment]
More specifically:
![image](https://user-images.githubusercontent.com/43292936/154337768-8dc11ab5-a6c3-439d-a98a-5f7e7af6accf.png)

**Comment by koshaan** [comment]
Arguments for choice of DigitalOcean

DigitalOcean targets smaller developers and projects, very fitting for our course, where a competitor like AWS is more focused on larger use-cases. Another reason for picking DigitalOcean for this project, is price. We get $100 free credits for the service through GitHub Student Pack, where we could only get $35 on Amazon. Microsoft Azure could also provide $100 in free credits, however their services cost from $15 a month, where DigitalOcean goes down to $5, which means we would have to migrate accounts much less throughout the project, if/when we run out of funds. The price for a PostgreSQL server is $15 monthly on DigitalOcean, where a comparably server is $37 monthly on Microsoft Azure, which is another reason as to why DigitalOcean is preferable, as it is nice to keep both the VPS and the database on the same platform.
DigitalOcean also provides a very easy to use interface, and one-click deployments, which is a huge benefit under time pressure of getting the project up and running. This applied to both their droplets (VPS), and for a PostgreSQL database, which meant that it was very quick to get everything up and running, while remaining cheap.
Exercise script also targets DigitalOcean, making it much easier to adapt to our project, as we had some boiler plate to relate to and use as a springboard. 
Lastly, the course manager recommended us to use DigitalOcean.

**Comment by ChadIImus** [comment]
If possible, provision droplets in a specific region like europe or even country like germany.
Gives us a better response time for simulator requests.
