### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by koshaan** [ChadIImus/Devoops#5]
(pbkdf2:sha256 algorithm)

Add authentication that uses this algorithm and a session variable to authenticates users

**Comment by ChadIImus** [comment]
Did initial aspnet identity.
needs:
login 
logoff

get id from auth

users are only allowed if logged in
and anonymous are allowed for those that they need

handling if passwordhash null in login

**Comment by julianbrandt** [comment]
All the above things are done, with the exception of checking for allowanonymous/allowed if logged in. I could not get the login state to work just using postman, but it does not seem like requests are blocked by there not being an [AllowAnonymous] attribute. We should look into this when the frontend is done, so we can actually work with the state (cookie).
